language: node_js
sudo: false
node_js:
- iojs
before_script:
- npm install -g grunt-cli gitbook-cli
- npm install
- gitbook install book
- gem install dotenv aws-sdk thread bundler git mime
after_success:
- |
  ./deploy.rb
matrix:
  fast_finish: true
env:
  global:
    - BUCKET=dev.px4.io
    - secure: "h56N4BV2y74Pm378q6HZlCK6TVogVbsaOIbPIGFF5ijglVi8yAHOr/OeZJh003m0Pn51Te5Ov6ZMxOR1YR6pZepH72YswlP2jEHU+8yOAn0sxibGMf+He+gBjRaNdIljOFmxsyVJqdoHkAnaTbl48mkTqZUZdHoxdj0O5hCXb47ivre9y+j2Z7oe88ovGQCfQXrjHktGMEUAv7Zx/Ih+zXtgIfnQxmUzc2I3cyImaq2hGmcQuvCN1+tjjy6QHpbrfXAiMXheZTPftpYLL61wlGkKtTxG5bq5F7gIBhh2dWrj0bqnFtrnjta+9XrGbkZ+kaxYTcoBZYDAaC7yFQfOFsDNIwRPHenr01XWkLQFzWHY1f/T1P7S2CPoy17OMx7lbK7KEyFpMPTlSDiHhYZ0PIwZMw4f3MPFhr6al/kpJ7JMrtR/1wRzNrrSl+ECDJGfPDcFFr4mKZtFBt017osOD5x0cOWaNbzLW9Uac3d/3/6j8dy8p6ad+UTKlEOlqRo8H8auCG4bnLI8t0jUdOVZmVyaI7O4OBIkPke52aT9DfvxCMiIsaf92JJVU7h6uY2z6o9KEv7ejRN6P3zKnKLX+zhpuFUEHi6DGtfJ8HGq/0Uz1DXAB0zkyuT7L5nzKwCa2AflaVVqlpqYiSMwojDG7fn+VOAIfhSrZyVsH5oNs0M="
    - secure: "AsRQU8RrPVvipFH+0VHJHyApI1m+Jb8g2sd7RpSZTIx9Hfln6N6rGZzZO5J1qAFOxTd6mvoHawBLTebPxUsqXkhbZZVLdj0zFXJH2xua9aYR1gjHhvtAWabo0X5NpvlHQjAB+ra2uW9ONjJJw9SsJq8sF/Vzw4KIfCzadEcNlrhVaxjIePeGE4Qu3i2SU1C1+uvaaVvY+y8ZGZoruEpmnpSq6xwG42g/xWJjcOp79vLVjMEr0I2YzjIZyS4ssK83JO/EcHsscDjLSS2DwP6iLbtp5yJ5Gc7QDUpDslVleCd1cugF4tz4zauJqVUnShcZAUiYv2rDYO6vcElWXnAXvdqUusW/+tywHWsGfIY/kN7VkQA0tuhKOWgr/aVTTUkf9YOGISQVrR/u+62AA+QzSjMMVHISKsP453FIUN8WdDlsG4iPP3Yp7TqyjMxcnZ3MJAmau9TbymVvukZzdpD7+qGVduQX1xinf+PZuvA5YaEDHTewJi+SSIxsXE5RO9cLZZnlaBm1j6KBNfey5R817YWJe3yW9q53++UgsDnfVXeewCExm4NjyJVFYJE7n0hIO+hAsL9Y4Cy3n1hDR5151KMgu4IveQ50rMeYjVcdSWzR7NZpXLO3gO9U157YObtnDVx2As434kdykFi/p+FB1TH5fophS9sBsf//h5jRYMY="